-- MySQL Script generated by MySQL Workbench
-- Wed Apr  3 13:38:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema base_argio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema base_argio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `base_argio` DEFAULT CHARACTER SET utf8 ;
USE `base_argio` ;

-- -----------------------------------------------------
-- Table `base_argio`.`arco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_argio`.`ARCO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_TEMATICA` INT(11) NULL DEFAULT NULL,
  `ID_LIDER` INT(11) NULL DEFAULT NULL,
  `DATA_HORA` VARCHAR(245) NULL DEFAULT NULL,
  `SITUACAO` INT(11) NULL DEFAULT NULL,
  `CODIGO_EQUIPE` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 81
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base_argio`.`classificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_argio`.`CLASSIFICACAO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  `ID_OPINIAO` INT(11) NULL DEFAULT NULL,
  `TIPO` INT(11) NULL DEFAULT NULL,
  `MOTIVO` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base_argio`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_argio`.`COMENTARIO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  `ID_OPINIAO` INT(11) NULL DEFAULT NULL,
  `TEXTO` TEXT NULL DEFAULT NULL,
  `DATA_HORA` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base_argio`.`curtida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_argio`.`CURTIDA` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  `ID_OPINIAO` INT(11) NULL DEFAULT NULL,
  `CURTIU` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 114
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base_argio`.`denuncia_opiniao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_argio`.`DENUNCIA_OPINIAO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  `ID_OPINIAO` INT(11) NULL DEFAULT NULL,
  `TEXTO` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base_argio`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_argio`.`EQUIPE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CODIGO` VARCHAR(254) NULL DEFAULT NULL,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  `SITUACAO` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 161
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base_argio`.`escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_argio`.`ESCOLARIDADE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `INSTITUICAO` VARCHAR(245) NULL DEFAULT NULL,
  `AREA` VARCHAR(245) NULL DEFAULT NULL,
  `ANO` VARCHAR(245) NULL DEFAULT NULL,
  `GRUPOS` TEXT NULL DEFAULT NULL,
  `DESCRICAO` TEXT NULL DEFAULT NULL,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base_argio`.`especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_argio`.`ESPECIALIDADE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(245) NULL DEFAULT NULL,
  `ESTRELAS` INT(11) NULL DEFAULT NULL,
  `CURTIDAS` INT(11) NULL DEFAULT NULL,
  `NIVEL` INT(11) NULL DEFAULT NULL,
  `TIPO_USUARIO` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base_argio`.`especialidade_do_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_argio`.`ESPECIALIDADE_DO_USUARIO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  `ID_ESPECIALIDADE` INT(11) NULL DEFAULT NULL,
  `ESTRELAS` INT(11) NULL DEFAULT NULL,
  `CURTIDAS` INT(11) NULL DEFAULT NULL,
  `CODIGO_ETAPA` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base_argio`.`estrela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_argio`.`ESTRELA` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  `ID_OPINIAO` INT(11) NULL DEFAULT NULL,
  `QUANTIDADE` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 123
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base_argio`.`etapa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_argio`.`ETAPA` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_ARCO` INT(11) NULL DEFAULT NULL,
  `NOME` VARCHAR(245) NULL DEFAULT NULL,
  `DESCRICAO_LIDER` TEXT NULL DEFAULT NULL,
  `SITUACAO` INT(11) NULL DEFAULT NULL,
  `CODIGO` INT(11) NULL DEFAULT NULL,
  `DESCRICAO_MENBRO` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 376
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base_argio`.`notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_argio`.`NOTIFICACAO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_ARCO` INT(11) NULL DEFAULT NULL,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  `TEXTO` TEXT NULL DEFAULT NULL,
  `DATA_HORA` VARCHAR(45) NULL DEFAULT NULL,
  `SITUACAO` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 135
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base_argio`.`opiniao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_argio`.`OPINIAO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_ETAPA` INT(11) NULL DEFAULT NULL,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  `DATA_HORA` VARCHAR(245) NULL DEFAULT NULL,
  `SITUACAO` INT(11) NULL DEFAULT NULL,
  `TEXTO` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 113
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base_argio`.`tematica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_argio`.`TEMATICA` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(245) NULL DEFAULT NULL,
  `DESCRICAO` TEXT NULL DEFAULT NULL,
  `IDADE_MINIMA` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base_argio`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_argio`.`USUARIO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(245) NULL DEFAULT NULL,
  `SOBRENOME` VARCHAR(245) NULL DEFAULT NULL,
  `ESCOLARIDADE` VARCHAR(245) NULL DEFAULT NULL,
  `CPF` VARCHAR(245) NULL DEFAULT NULL,
  `DATA_NASC` VARCHAR(245) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(245) NULL DEFAULT NULL,
  `SENHA` VARCHAR(245) NULL DEFAULT NULL,
  `SEXO` VARCHAR(1) NULL DEFAULT NULL,
  `BIO` TEXT NULL DEFAULT NULL,
  `TIPO` INT(11) NULL DEFAULT NULL,
  `SITUACAO` INT(11) NULL DEFAULT NULL,
  `ONLINE` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;

USE `base_argio` ;

-- -----------------------------------------------------
-- procedure SITUACAO_ARCO
-- -----------------------------------------------------

DELIMITER $$
USE `base_argio`$$
CREATE PROCEDURE `SITUACAO_ARCO`(IN X INT)
BEGIN
   IF(SELECT COUNT(SITUACAO) AS RESULT FROM ETAPA WHERE ID_ARCO = X AND SITUACAO = 2 HAVING COUNT(SITUACAO) = 5)
    then 
        UPDATE ARCO SET SITUACAO = 2 WHERE ID = X;
        SELECT 'ESTÁ COMPLETO' as Msg;
    else 
		SELECT 'NÃO ESTÁ COMPLETO' as Msg;
    END IF;

END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
