-- MySQL Script generated by MySQL Workbench
-- Wed Mar 27 23:12:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd` DEFAULT CHARACTER SET utf8 ;
USE `bd` ;

-- -----------------------------------------------------
-- Table `bd`.`arco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`arco` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_TEMATICA` INT(11) NULL DEFAULT NULL,
  `ID_LIDER` INT(11) NULL DEFAULT NULL,
  `DATA_HORA` VARCHAR(245) NULL DEFAULT NULL,
  `SITUACAO` INT(11) NULL DEFAULT NULL,
  `CODIGO_EQUIPE` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`classificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`classificacao` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  `ID_OPINIAO` INT(11) NULL DEFAULT NULL,
  `TIPO` INT(11) NULL DEFAULT NULL,
  `MOTIVO` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`curtida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`curtida` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  `ID_OPINIAO` INT(11) NULL DEFAULT NULL,
  `CURTIU` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`denuncia_opiniao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`denuncia_opiniao` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  `ID_OPINIAO` INT(11) NULL DEFAULT NULL,
  `TEXTO` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`equipe` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CODIGO` VARCHAR(254) NULL DEFAULT NULL,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  `SITUACAO` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 146
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`escolaridade` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `INSTITUICAO` VARCHAR(245) NULL DEFAULT NULL,
  `AREA` VARCHAR(245) NULL DEFAULT NULL,
  `ANO` VARCHAR(245) NULL DEFAULT NULL,
  `GRUPOS` TEXT NULL DEFAULT NULL,
  `DESCRICAO` TEXT NULL DEFAULT NULL,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`especialidade` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(245) NULL DEFAULT NULL,
  `DESCRICAO` VARCHAR(245) NULL DEFAULT NULL,
  `CODIGO` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`especialidade_do_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`especialidade_do_usuario` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  `ID_OPINIAO` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`estrela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`estrela` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  `ID_OPINIAO` INT(11) NULL DEFAULT NULL,
  `QUANTIDADE` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 70
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`etapa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`etapa` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_ARCO` INT(11) NULL DEFAULT NULL,
  `NOME` VARCHAR(245) NULL DEFAULT NULL,
  `DESCRICAO_LIDER` TEXT NULL DEFAULT NULL,
  `SITUACAO` INT(11) NULL DEFAULT NULL,
  `CODIGO` INT(11) NULL DEFAULT NULL,
  `DESCRICAO_MENBRO` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 341
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`notificacao` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_ARCO` INT(11) NULL DEFAULT NULL,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  `TEXTO` TEXT NULL DEFAULT NULL,
  `DATA_HORA` VARCHAR(45) NULL DEFAULT NULL,
  `SITUACAO` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 119
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`opiniao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`opiniao` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_ETAPA` INT(11) NULL DEFAULT NULL,
  `ID_USUARIO` INT(11) NULL DEFAULT NULL,
  `DATA_HORA` VARCHAR(245) NULL DEFAULT NULL,
  `SITUACAO` INT(11) NULL DEFAULT NULL,
  `TEXTO` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 84
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`tematica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`tematica` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(245) NULL DEFAULT NULL,
  `DESCRICAO` TEXT NULL DEFAULT NULL,
  `IDADE_MINIMA` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`usuario` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(245) NULL DEFAULT NULL,
  `SOBRENOME` VARCHAR(245) NULL DEFAULT NULL,
  `ESCOLARIDADE` VARCHAR(245) NULL DEFAULT NULL,
  `CPF` VARCHAR(245) NULL DEFAULT NULL,
  `DATA_NASC` VARCHAR(245) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(245) NULL DEFAULT NULL,
  `SENHA` VARCHAR(245) NULL DEFAULT NULL,
  `SEXO` VARCHAR(1) NULL DEFAULT NULL,
  `BIO` TEXT NULL DEFAULT NULL,
  `TIPO` INT(11) NULL DEFAULT NULL,
  `SITUACAO` INT(11) NULL DEFAULT NULL,
  `ONLINE` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
