CREATE SCHEMA IF NOT EXISTS `BD`char set = utf8 DEFAULT COLLATE win1252;
USE `BD` ;

CREATE TABLE IF NOT EXISTS `BD`.`USUARIO` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(245),
    `SOBRENOME` VARCHAR(245),
    `ESCOLARIDADE` VARCHAR(245),
    `CPF` VARCHAR(245),
    `DATA_NASC` VARCHAR(245),
	`EMAIL` VARCHAR(245),
    `SENHA` VARCHAR(245),
    `SEXO` VARCHAR(1),
	`BIO` TEXT,
    `TIPO` INT,
    `SITUACAO` INT,
    `ONLINE` INT,
  PRIMARY KEY (`ID`))
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `BD`.`ESCOLARIDADE` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
    `INSTITUICAO` VARCHAR(245),
    `AREA` VARCHAR(245),
	`ANO` VARCHAR(245),
    `GRUPOS` TEXT,
    `DESCRICAO` TEXT,
    `ID_USUARIO` INT(11),
  PRIMARY KEY (`ID`))
  DEFAULT CHARSET = utf8;